# Generated by Django 5.0.14 on 2025-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team_description_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
