# Generated by Django 5.0.14 on 2025-05-07 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_team_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
