# Generated by Django 5.0.14 on 2025-05-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teaminvitation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='type',
            field=models.CharField(choices=[('ToTeam', 'User → Team'), ('ToUser', 'Team → User')], default='ToUser', max_length=10),
        ),
    ]
