# Generated by Django 5.0.14 on 2025-05-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_team_draws_team_losses_team_matches_played_team_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_team_name', models.CharField(max_length=100)),
                ('match_format', models.CharField(choices=[('5v5', '5v5'), ('6v6', '6v6'), ('7v7', '7v7'), ('11v11', '11v11')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('payment_condition', models.CharField(choices=[('lose_to_pay', 'Lose to pay'), ('50_50', '50/50 split'), ('70_30', '70/30 split')], max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_matches', to='core.team')),
            ],
        ),
    ]
