# Generated by Django 5.0.14 on 2025-05-11 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_openmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openmatch',
            name='opponent_team_name',
        ),
        migrations.RemoveField(
            model_name='openmatch',
            name='status',
        ),
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('open_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to='core.openmatch')),
                ('requesting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_match_requests', to='core.team')),
            ],
        ),
    ]
