# Generated by Django 5.0.14 on 2025-05-11 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_openmatch_opponent_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='match_format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='target_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_requests', to='core.team'),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='open_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to='core.openmatch'),
        ),
    ]
