# Generated by Django 5.0.14 on 2025-05-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_openmatch_confirmed_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='requesting_team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='target_team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
