# Generated by Django 5.0.14 on 2025-05-13 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_matchrequest_requesting_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='match_format',
            field=models.CharField(blank=True, choices=[('5v5', '5v5'), ('7v7', '7v7'), ('11v11', '11v11')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PendingLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_type', models.CharField(choices=[('requesting', 'Requesting Team'), ('target', 'Target Team')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=10)),
                ('match_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_lineups', to='core.matchrequest')),
                ('players', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
