# Generated by Django 5.0.14 on 2025-05-13 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_matchrequest_match_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinglineup',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='pending_lineups', to=settings.AUTH_USER_MODEL),
        ),
    ]
