# Generated by Django 5.0.14 on 2025-05-13 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_pendinglineup_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingLineupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('pendinglineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pendinglineup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games_pendinglineup_players',
                'unique_together': {('pendinglineup', 'user')},
            },
        ),
        migrations.AlterField(
            model_name='pendinglineup',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='pending_lineups', through='core.PendingLineupPlayer', to=settings.AUTH_USER_MODEL),
        ),
    ]
