# Generated by Django 5.0.14 on 2025-05-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pendinglineupplayer_alter_pendinglineup_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinglineupplayer',
            name='pendinglineup',
        ),
        migrations.AlterUniqueTogether(
            name='pendinglineupplayer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pendinglineupplayer',
            name='user',
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='match_format',
            field=models.CharField(blank=True, choices=[('5v5', '5v5'), ('6v6', '6v6'), ('7v7', '7v7'), ('11v11', '11v11')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='PendingLineup',
        ),
        migrations.DeleteModel(
            name='PendingLineupPlayer',
        ),
    ]
