# Generated by Django 5.0.14 on 2025-05-14 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_pendinglineupplayer_pendinglineup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='requesting_confirmed_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='requesting_required_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='requesting_status',
            field=models.CharField(default='incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='target_confirmed_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='target_required_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='target_status',
            field=models.CharField(default='incomplete', max_length=20),
        ),
        migrations.CreateModel(
            name='MatchJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_side', models.CharField(choices=[('requesting', 'Requesting'), ('target', 'Target')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matchrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
