# Generated by Django 5.0.14 on 2025-05-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_matchrequest_requesting_substitution_filled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrequest',
            name='requesting_substitution_filled',
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='requesting_substitution_slots',
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='target_substitution_filled',
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='target_substitution_slots',
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='requesting_confirmed_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='requesting_required_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='requesting_status',
            field=models.CharField(default='incomplete', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='target_confirmed_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='target_required_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='target_status',
            field=models.CharField(default='incomplete', max_length=20),
        ),
    ]
